spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'koochita'

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

  application:
    name: 'room'

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: 'DEBUG'

eureka:
  client:
    serviceUrl:
      defaultZone: "http://admin:123@localhost:8761"
    fetch-registry: false
    register-with-eureka: false
