spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'room'

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: 'DEBUG'
